[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
postgres = "0.19.9"
rust_xlsxwriter = { version = "0.80.0", features = ["zlib"] }
serde = "1.0.217"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.19"
